### ISSUE TITLE
一些改进

### ISSUE THREAD

**Issue by ZhuYuxuan9302** [MineJPGcraft/ServerListSync#1]
是否可以额外添加对1.21.3的支持
同时对输出的默认配置文件中定义默认服务器列表随机排序和服务器列表的链接
以及是否可以提供对Mod menu中的配置编辑支持

**Comment by ZhuYuxuan9302** [comment]
默认配置已完成，1.21.3即将支持

**Comment by alazeprt** [comment]
配置界面当前仅支持1.21.1，可在Github Actions内下载
